---
format: html
server: shiny
include-before-body: hide_pages.js
filters:
  - split_pages.lua
execute: 
  echo: false
---

```{r}
#| context: setup
#| echo: false
#| warning: false
#| message: false

source('functions.R')
useShinyjs(rmd = TRUE)
```

::: {#welcome .sd-page}

# Welcome to my survey! 

Here is a question to get started 

```{r}
sd_question(
  name     = 'color',
  type     = 'mc',
  required = TRUE,
  label    = "Do you want to take the red pill or the blue pill?",
  option   = c(
    'Blue' = 'blue', 
    'Red' = 'red'
  )
)
```

Here is another question to test skip logic:

```{r}
sd_question(
  name     = 'skip',
  type     = 'mc',
  required = TRUE,
  label    = "Do you want to skip to another page?",
  option   = c(
    'No' = 'no', 
    'Yes, take me to page 3!' = 'pg3', 
    'Yes, take me to the end!' = 'end'
  )
)
```

Here is a question to showcase conditional display logic. If you choose "Yes" to the question below, another question will appear below it:

```{r}
sd_question(
  name = "have_pet",
  type = "mc",
  label = "Do you have a pet?",
  option = c(
    "No" = "no",
    "Yes" = "yes"
  )
)

sd_question(
  name = "pet_name",
  type = "text",
  label = "What's your pet's name?"
)
```

<center>
Page: 1
</center>

:::

::: {#demographics .sd-page}

## Tell us abour yourself!

```{r}
sd_question(
  name     = 'age',
  type     = 'text',
  required = TRUE,
  label    = "What's your age?",
  option   = NULL
)

sd_question(
  name     = 'gender',
  type     = 'mc',
  required = TRUE,
  label    = "Which best describes your gender?",
  option   = c(
    "Female" = "female",
    "Male" = "male",
    "Prefer not to say" = "opt_out"
  )
)
```

<center>
Page: 2
</center>

:::

::: {#animals .sd-page}

## Here are a few more questions to finish up!

```{r}
sd_question(
  name     = 'animal',
  type     = 'text',
  required = FALSE,
  label    = "What's your favorite animal?"
)

sd_question(
  name     = 'education',
  type     = 'select',
  required = TRUE,
  label    = "What is the highest level of education you have attained?",
  option   = c(
    "Did not attend high school" = "hs_no",
    "Some high school"           = "hs_some",
    "High school graduate"       = "hs_grad",
    "Some college"               = "college_some",
    "College"                    = "college_grad",
    "Graduate Work"              = "grad",
    "Prefer not to say"          = "no_response"
  )
)
```

<center>
Page: 3
</center>

:::

::: {#end .sd-page}

## Thanks for taking our survey!

<center>
Page: 4
</center>

:::

```{r}
#| context: server

sd_server(
  input = input,
  session = session,
  question_ids = list(
    'color', 'skip', 'have_pet', 'pet_name','age', 'gender', 'animal',
    'education'
  ),
  skip_logic = tibble::tribble(
    ~question_id, ~response_value, ~target_page,
    "skip",       "pg3",           "animals",
    "skip",       "end",           "end"
  )
  # showif = tibble::tribble(
  #   ~question_id, ~question_dependence, ~response_value,
  #   "pet_name",   "have_pet",           "yes"
  # )
)
```
