---
format: html
echo: false
warning: false
---

```{r}
library(surveydown)
```

::: {#initial_page .sd-page}

# Initial Information

Please provide your initial information.

```{r}
sd_question(
  type   = 'text',
  id     = 'name',
  label  = 'Your Name:'
)

sd_question(
  type   = 'text',
  id     = 'email',
  label  = 'Your Email:'
)

sd_next()
```

:::

::: {#details_page .sd-page}

# Additional Details

Please provide some additional details.

```{r}
sd_question(
  type   = 'textarea',
  id     = 'feedback',
  label  = 'Please provide your feedback:'
)

sd_next()
```

:::

::: {#revision_page .sd-page}

# Review Your Submission

Please review your submission before finalizing.

```{r}
sd_output("name", type = "value")
sd_output("email", type = "value")
sd_output("feedback", type = "value")

sd_question(
  type   = 'mc',
  id     = 'needs_correction',
  label  = 'Do you need to correct your initial information (name/email)?',
  option = c(
    'Yes'  = 'yes',
    'No'   = 'no'
  )
)

sd_question(
  type   = 'mc',
  id     = 'needs_revision',
  label  = 'Do you need to revise your feedback?',
  option = c(
    'Yes'  = 'yes',
    'No'   = 'no'
  )
)

sd_next()
```

:::

::: {#confirmation_page .sd-page}

# Confirmation

Your submission has been received. Thank you!

```{r}
sd_close("Exit Survey")
```

:::
