---
format: html
server: shiny
include-before-body: pagination.js
execute: 
  echo: false
---

```{r}
#| context: setup
#| echo: false
#| warning: false
#| message: false

library(shiny)
library(shinyjs)

useShinyjs(rmd = TRUE)

source('functions.R')
```

::: {#page-1}

# Welcome to my survey! 

Here is a question to get started 

```{r}
sd_question(
  name     = 'color',
  type     = 'mc',
  required = TRUE,
  label    = "Do you want to take the red pill or the blue pill?",
  option   = c(
    'Blue' = 'blue', 
    'Red' = 'red'
  )
)

sd_next(1)
```

:::

::: {#page-2}

## Tell us abour yourself!

```{r}
sd_question(
  name     = 'age',
  type     = 'text',
  required = TRUE,
  label    = "What's your age?",
  option   = NULL
)

sd_question(
  name     = 'gender',
  type     = 'mc',
  required = TRUE,
  label    = "Which best describes your gender?",
  option   = c(
    "Female" = "Female",
    "Male" = "Male",
    "Prefer not to say" = "opt_out"
  )
)

sd_next(2)
```

:::

::: {#page-3}

Here are a few more questions to finish up! 

```{r}
sd_question(
  name     = 'animal',
  type     = 'text',
  required = FALSE,
  label    = "What's your favorite animal?"
)

sd_question(
  name     = 'education',
  type     = 'select',
  required = TRUE,
  label    = "What is the highest level of education you have attained?",
  option   = c(
    "Did not attend high school" = "hs_no",
    "Some high school"           = "hs_some",
    "High school graduate"       = "hs_grad",
    "Some college"               = "college_some",
    "College"                    = "college_grad",
    "Graduate Work"              = "grad",
    "Prefer not to say"          = "no_response"
  )
)

sd_next(3)
```

:::

::: {#page-4}

# Thanks for taking our survey!

:::

```{r}
#| context: server

sd_server(
  question_ids = list(
    'color', 'age', 'gender', 'animal', 'education'
  ),
  n_pages = 4,
  input = input, 
  session = session
)
```
